---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: my-database-backup
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: database-backup
            image: asafjafarli/mysqlbackup:v1
            imagePullPolicy: Always
            env:
              - name: AWS_ACCESS_KEY_ID
                value: AKIAQ643TFZMCQECM7QO
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                   secretKeyRef:
                     name: database-backup
                     key: aws_secret_access_key
              - name: AWS_DEFAULT_REGION
                value: "us-east-2"
              - name: AWS_BUCKET_NAME
                value: "asef-backups"
              - name: AWS_BUCKET_BACKUP_PATH
                value: "/mysql"
              - name: TARGET_DATABASE_HOST
                value: "mysql"
              - name: TARGET_DATABASE_PORT
                value: "3306"
              - name: TARGET_DATABASE_NAMES
                value: "ktask-db"
              - name: TARGET_DATABASE_USER
                value: "root"
              - name: TARGET_DATABASE_PASSWORD
                valueFrom:
                   secretKeyRef:
                     name: database-backup
                     key: database_password
              - name: BACKUP_TIMESTAMP
                value: "_%Y_%m_%d"
              - name: SLACK_ENABLED
                value: "false"
          restartPolicy: Never
