apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
      - name: busybox
        image: busybox:latest
        args: ["rm", "-rf", "/var/lib/postgresql/data/lost+found"]
        volumeMounts:
          - name: postgres-persistent-storage
            mountPath: /var/lib/postgresql/data
      containers:
      - name: postgres
        image: postgres
        env:
          - name: POSTGRES_PASSWORD
            value: password12
          - name: POSTGRES_USER
            value: root
        volumeMounts:
          - name: postgres-persistent-storage
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-persistent-storage
          # pointer to the configuration of HOW we want the mount to be implemented
          persistentVolumeClaim:
            claimName: postgres-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: ktask-postgres
spec:
  selector:
    app: postgres
  ports:
    - name: postgresport
      port: 5432
  type: ClusterIP

